fragment NavigationParts on Navigation {
  __typename
  header {
    __typename
    links {
      __typename
      text
      href
      links {
        __typename
        text
        href
        links {
          __typename
          text
          href
        }
      }
    }
    actions {
      __typename
      text
      href
      variant
    }
  }
  footer {
    __typename
    links {
      __typename
      title
      links {
        __typename
        text
        href
      }
    }
    secondaryLinks {
      __typename
      text
      href
    }
    footNote
  }
}

fragment PagesParts on Pages {
  __typename
  metadata {
    __typename
    title
  }
  hero {
    __typename
    title1
    title2
    subtitle
    images {
      __typename
      src
      alt
    }
    actions {
      __typename
      text
      href
      variant
      icon
    }
  }
  stats {
    __typename
    title
    amount
    icon
  }
  facultyMessages {
    __typename
    title
    messages {
      __typename
      name
      role
      department
      image
      message
    }
  }
  features {
    __typename
    tagline
    title
    subtitle
    items {
      __typename
      title
      description
      icon
    }
  }
  about {
    __typename
    tagline
    title
    subtitle
    description
    image {
      __typename
      src
      alt
    }
    items {
      __typename
      title
      description
    }
  }
  cta {
    __typename
    title
    subtitle
    actions {
      __typename
      text
      href
      variant
      icon
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  videoUrl
  slug
  publishDate
  image
  category
  body
}

fragment WingParts on Wing {
  __typename
  title
  videoUrl
  slug
  body
}

fragment EventParts on Event {
  __typename
  title
  videoUrl
  slug
  date
  image
  coverImage
  metadata {
    __typename
    title
    description
  }
  body
}

fragment CommitteeParts on Committee {
  __typename
  title
  slug
  presidentialPanel {
    __typename
    name
    role
    image
    facebook
    email
    linkedin
  }
  vicePresidents {
    __typename
    name
    role
    image
    facebook
    email
    linkedin
  }
}

fragment LegalParts on Legal {
  __typename
  title
  videoUrl
  slug
  body
}

fragment PortfolioParts on Portfolio {
  __typename
  title
  coverImage
  years {
    __typename
    year
    link
  }
}
